### ISSUE TITLE
Notes for map-in-your-mind

### ISSUE THREAD

**Issue by oboulton** [awesomephant/map-in-your-mind#1]
Notes for Max
Preview:
— project spacing too large on mobile size (see image i sent on whatsapp); also 'project 1' has a particularly large gap between the title and project image.
— centre project counter alignment — seems to fall down as the window is shrunk, particularly on mobile size (see whatsapp image)
— (mobile) its difficult to scroll because of the project flicking mechanism—could be just 'swiped' for mobile. Im not sure what you think about this? lets talk about this one as im not sure what to do.. I can also explain better on skype. 

Info:
— with the amended (now longer) colophon the type spills off the page. Can we stop this from happening so it was as it was before sitting flush in one fixed window.
— The buttons for the header don’t work on mobile when you've scrolled down window.

Directory:
— still opening some projects in the middle can we make it start from the top?
— Perspective gif (is there a way to make it run on loop, or is that something I have to do when exporting?
— On mobile is there a way to carry over the project info onto the project page. For example when you click on a book it would be good to be able to read all of the information when 'inside' a project i.e the printing, edition, type of book ect. (lets speak about this one)
— on mobile could we make the read projects a colour when you have ‘viewed’ them? (lets speak about this one)
— .pdf’s don’t download—Im guessing this is a similar issue to what we had with the .gif's

Global issues:
— All the helvetica caps across the site have moved to bold (see image i sent on whatsapp) (this has something to do with when we changed the spacing for everson.
— Should all everson type go bold on mobile? (lets speak about this one)
— are glyphs randomly positioned now? / are they classed as a pop up? (lets speak about this one)

**Comment by awesomephant** [comment]
Going to close this and split into individual issues.
